### ISSUE TITLE
a new roadmap

### ISSUE THREAD

**Issue by goldamperage** [833FCAK3/eng_new_words#1]
I think you must improve this program.

I want to propose a roadmap. 

1) To make a help module.
2) To make an automatic translation unknown words (english+russian)
3) To make excellent output in html file. Maybe you can use pandas library

Good luck.

**Comment by goldamperage** [comment]
I am so fucking angry. Where is my program?

**Comment by 833FCAK3** [comment]
Where is my money?
--
Sent from Mail.ru app for Android Friday, 24 December 2021, 07:32pm +05:00 from goldamperage  ***@***.*** :

**Comment by goldamperage** [comment]
I paid you by my support 
Where is my fucking program?

**Comment by 833FCAK3** [comment]
No money no program
--
Sent from Mail.ru app for Android Friday, 24 December 2021, 08:43pm +05:00 from goldamperage  ***@***.*** :

**Comment by goldamperage** [comment]
Github will delete your account. You shame Github.

**Comment by goldamperage** [comment]
![image](https://user-images.githubusercontent.com/65466593/147363222-002f3821-9fd3-4d0e-928b-5fcfc8086474.png)

**Comment by 833FCAK3** [comment]
Github can eat my ass
--
Sent from Mail.ru app for Android Friday, 24 December 2021, 08:53pm +05:00 from goldamperage  ***@***.*** :

**Comment by 833FCAK3** [comment]
What the fuck is it that you dont have camwhore?
--
Sent from Mail.ru app for Android Friday, 24 December 2021, 08:54pm +05:00 from goldamperage  ***@***.*** :

**Comment by goldamperage** [comment]
greedy person
